local M = {}

---@param p lumen.Palette
---@param o {transparent:boolean, italics:boolean, light:boolean, blend:fun(fg:string, bg:string, a:number):string}
function M.groups(p, o)
  local blend = o.blend
  local bg = o.transparent and "NONE" or p.bg
  local bg_float = o.transparent and "NONE" or p.bg_float
  local it = o.italics
  -- tinted background for diagnostics / diffs
  local function tint(c, a)
    return blend(c, p.bg, a or (o.light and 0.14 or 0.12))
  end

  local g = {
    -- ── editor ────────────────────────────────────────────────
    Normal = { fg = p.fg, bg = bg },
    NormalNC = { fg = p.fg, bg = bg },
    NormalFloat = { fg = p.fg, bg = bg_float },
    FloatBorder = { fg = p.border, bg = bg_float },
    FloatTitle = { fg = p.bg_dark, bg = p.accent, bold = true },
    FloatFooter = { fg = p.comment, bg = bg_float },
    Cursor = { fg = p.bg, bg = p.fg },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    TermCursor = { fg = p.bg, bg = p.accent },
    CursorLine = { bg = p.bg_hl },
    CursorColumn = { bg = p.bg_hl },
    ColorColumn = { bg = p.bg_hl },
    CursorLineNr = { fg = p.accent, bold = true },
    CursorLineSign = { bg = p.bg_hl },
    CursorLineFold = { fg = p.fg_dim, bg = p.bg_hl },
    LineNr = { fg = p.gutter },
    LineNrAbove = { fg = p.gutter },
    LineNrBelow = { fg = p.gutter },
    SignColumn = { fg = p.gutter, bg = bg },
    FoldColumn = { fg = p.gutter, bg = bg },
    Folded = { fg = p.fg_dim, bg = p.bg_hl },
    VertSplit = { fg = p.border },
    WinSeparator = { fg = p.border, bold = true },
    EndOfBuffer = { fg = p.bg },
    NonText = { fg = p.gutter },
    Whitespace = { fg = p.bg_sel },
    SpecialKey = { fg = p.gutter },
    Conceal = { fg = p.comment },
    Visual = { bg = p.bg_visual },
    VisualNOS = { bg = p.bg_visual },
    Search = { fg = p.fg_bright, bg = blend(p.accent, p.bg, 0.28) },
    IncSearch = { fg = p.bg_dark, bg = p.accent, bold = true },
    CurSearch = { link = "IncSearch" },
    Substitute = { fg = p.bg_dark, bg = p.rose },
    MatchParen = { fg = p.accent, bg = p.bg_sel, bold = true },
    QuickFixLine = { bg = p.bg_sel, bold = true },
    Directory = { fg = p.blue },
    Title = { fg = p.accent, bold = true },
    ErrorMsg = { fg = p.red },
    WarningMsg = { fg = p.yellow },
    ModeMsg = { fg = p.fg_dim, bold = true },
    MoreMsg = { fg = p.teal },
    Question = { fg = p.blue },
    MsgArea = { fg = p.fg },
    MsgSeparator = { fg = p.border },
    WildMenu = { bg = p.bg_sel },
    WinBar = { fg = p.fg_dim, bg = bg },
    WinBarNC = { fg = p.comment, bg = bg },
    StatusLine = { fg = p.fg_dim, bg = p.bg_dark },
    StatusLineNC = { fg = p.comment, bg = p.bg_dark },
    TabLine = { fg = p.comment, bg = p.bg_dark },
    TabLineFill = { bg = p.bg_dark },
    TabLineSel = { fg = p.fg_bright, bg = p.bg, bold = true },

    Pmenu = { fg = p.fg, bg = p.bg_float },
    PmenuSel = { bg = p.bg_sel, bold = true },
    PmenuKind = { fg = p.violet, bg = p.bg_float },
    PmenuKindSel = { fg = p.violet, bg = p.bg_sel },
    PmenuExtra = { fg = p.comment, bg = p.bg_float },
    PmenuExtraSel = { fg = p.comment, bg = p.bg_sel },
    PmenuSbar = { bg = p.bg_float },
    PmenuThumb = { bg = p.border },
    PmenuMatch = { fg = p.accent, bold = true },
    PmenuMatchSel = { fg = p.accent, bold = true },
    ComplMatchIns = { fg = p.comment },

    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.yellow, undercurl = true },
    SpellLocal = { sp = p.blue, undercurl = true },
    SpellRare = { sp = p.violet, undercurl = true },

    DiffAdd = { bg = tint(p.green, 0.16) },
    DiffChange = { bg = tint(p.blue, 0.1) },
    DiffDelete = { fg = blend(p.red, p.bg, 0.5), bg = tint(p.red, 0.12) },
    DiffText = { bg = tint(p.blue, 0.26) },
    Added = { fg = p.green },
    Changed = { fg = p.blue },
    Removed = { fg = p.red },
    diffAdded = { fg = p.green },
    diffRemoved = { fg = p.red },
    diffChanged = { fg = p.blue },
    diffFile = { fg = p.accent },
    diffLine = { fg = p.comment },

    -- ── syntax (legacy) ───────────────────────────────────────
    Comment = { fg = p.comment, italic = it },
    Constant = { fg = p.orange },
    String = { fg = p.green },
    Character = { fg = p.green },
    Number = { fg = p.orange },
    Boolean = { fg = p.orange },
    Float = { fg = p.orange },
    Identifier = { fg = p.fg },
    Function = { fg = p.blue },
    Statement = { fg = p.violet },
    Conditional = { fg = p.violet },
    Repeat = { fg = p.violet },
    Label = { fg = p.sky },
    Operator = { fg = p.cyan },
    Keyword = { fg = p.violet, italic = it },
    Exception = { fg = p.violet },
    PreProc = { fg = p.rose },
    Include = { fg = p.rose },
    Define = { fg = p.rose },
    Macro = { fg = p.rose },
    PreCondit = { fg = p.rose },
    Type = { fg = p.teal },
    StorageClass = { fg = p.violet },
    Structure = { fg = p.teal },
    Typedef = { fg = p.teal },
    Special = { fg = p.cyan },
    SpecialChar = { fg = p.cyan },
    Tag = { fg = p.rose },
    Delimiter = { fg = p.fg_dim },
    SpecialComment = { fg = p.comment, bold = true },
    Debug = { fg = p.orange },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { fg = p.gutter },
    Error = { fg = p.red },
    Todo = { fg = p.bg_dark, bg = p.accent, bold = true },

    -- ── treesitter ────────────────────────────────────────────
    ["@variable"] = { fg = p.fg },
    ["@variable.builtin"] = { fg = p.red, italic = it },
    ["@variable.parameter"] = { fg = p.param },
    ["@variable.parameter.builtin"] = { fg = p.param, italic = it },
    ["@variable.member"] = { fg = p.member },
    ["@property"] = { fg = p.member },
    ["@constant"] = { fg = p.orange },
    ["@constant.builtin"] = { fg = p.orange, bold = true },
    ["@constant.macro"] = { fg = p.rose },
    ["@module"] = { fg = p.sky },
    ["@module.builtin"] = { fg = p.sky, italic = it },
    ["@label"] = { fg = p.sky },
    ["@string"] = { fg = p.green },
    ["@string.documentation"] = { fg = p.comment, italic = it },
    ["@string.regexp"] = { fg = p.orange },
    ["@string.escape"] = { fg = p.cyan, bold = true },
    ["@string.special"] = { fg = p.cyan },
    ["@string.special.symbol"] = { fg = p.amber },
    ["@string.special.url"] = { fg = p.sky, underline = true },
    ["@string.special.path"] = { fg = p.sky },
    ["@character"] = { fg = p.green },
    ["@character.special"] = { fg = p.cyan },
    ["@boolean"] = { fg = p.orange, bold = true },
    ["@number"] = { fg = p.orange },
    ["@number.float"] = { fg = p.orange },
    ["@type"] = { fg = p.teal },
    ["@type.builtin"] = { fg = p.teal, italic = it },
    ["@type.definition"] = { fg = p.teal, bold = true },
    ["@attribute"] = { fg = p.amber },
    ["@attribute.builtin"] = { fg = p.amber, italic = it },
    ["@function"] = { fg = p.blue },
    ["@function.builtin"] = { fg = p.cyan },
    ["@function.call"] = { fg = p.blue },
    ["@function.macro"] = { fg = p.rose },
    ["@function.method"] = { fg = p.blue },
    ["@function.method.call"] = { fg = p.blue },
    ["@constructor"] = { fg = p.amber },
    ["@operator"] = { fg = p.cyan },
    ["@keyword"] = { fg = p.violet, italic = it },
    ["@keyword.coroutine"] = { fg = p.violet, italic = it },
    ["@keyword.function"] = { fg = p.violet, italic = it },
    ["@keyword.operator"] = { fg = p.violet },
    ["@keyword.import"] = { fg = p.rose },
    ["@keyword.type"] = { fg = p.violet },
    ["@keyword.modifier"] = { fg = p.violet },
    ["@keyword.repeat"] = { fg = p.violet },
    ["@keyword.return"] = { fg = p.violet, bold = true },
    ["@keyword.debug"] = { fg = p.orange },
    ["@keyword.exception"] = { fg = p.red },
    ["@keyword.conditional"] = { fg = p.violet },
    ["@keyword.conditional.ternary"] = { fg = p.cyan },
    ["@keyword.directive"] = { fg = p.rose },
    ["@punctuation.delimiter"] = { fg = p.fg_dim },
    ["@punctuation.bracket"] = { fg = p.fg_dim },
    ["@punctuation.special"] = { fg = p.cyan },
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { fg = p.comment, italic = it },
    ["@comment.error"] = { fg = p.bg_dark, bg = p.red, bold = true },
    ["@comment.warning"] = { fg = p.bg_dark, bg = p.yellow, bold = true },
    ["@comment.todo"] = { fg = p.bg_dark, bg = p.amber, bold = true },
    ["@comment.note"] = { fg = p.bg_dark, bg = p.teal, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { fg = p.amber, bold = true },
    ["@markup.heading.1"] = { fg = p.amber, bold = true },
    ["@markup.heading.2"] = { fg = p.blue, bold = true },
    ["@markup.heading.3"] = { fg = p.violet, bold = true },
    ["@markup.heading.4"] = { fg = p.teal, bold = true },
    ["@markup.heading.5"] = { fg = p.rose, bold = true },
    ["@markup.heading.6"] = { fg = p.orange, bold = true },
    ["@markup.quote"] = { fg = p.fg_dim, italic = true },
    ["@markup.math"] = { fg = p.cyan },
    ["@markup.link"] = { fg = p.sky },
    ["@markup.link.label"] = { fg = p.sky },
    ["@markup.link.url"] = { fg = p.sky, underline = true },
    ["@markup.raw"] = { fg = p.green },
    ["@markup.raw.block"] = { fg = p.fg },
    ["@markup.list"] = { fg = p.amber },
    ["@markup.list.checked"] = { fg = p.green },
    ["@markup.list.unchecked"] = { fg = p.fg_dim },
    ["@diff.plus"] = { fg = p.green },
    ["@diff.minus"] = { fg = p.red },
    ["@diff.delta"] = { fg = p.blue },
    ["@tag"] = { fg = p.rose },
    ["@tag.builtin"] = { fg = p.rose },
    ["@tag.attribute"] = { fg = p.amber, italic = it },
    ["@tag.delimiter"] = { fg = p.fg_dim },

    -- ── lsp semantic tokens ───────────────────────────────────
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = {},
    ["@lsp.type.decorator"] = { link = "@attribute" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.interface"] = { fg = p.teal, italic = it },
    ["@lsp.type.keyword"] = { link = "@keyword" },
    ["@lsp.type.macro"] = { link = "@function.macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { fg = p.teal, italic = it },
    ["@lsp.type.variable"] = {},
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.readonly"] = { fg = p.fg, bold = false },
    ["@lsp.mod.deprecated"] = { strikethrough = true },
    LspReferenceText = { bg = p.bg_sel },
    LspReferenceRead = { bg = p.bg_sel },
    LspReferenceWrite = { bg = p.bg_sel, underline = true, sp = p.accent },
    LspSignatureActiveParameter = { fg = p.accent, bold = true, underline = true },
    LspCodeLens = { fg = p.comment },
    LspInlayHint = { fg = p.comment, bg = blend(p.bg_hl, p.bg, 0.6), italic = it },
    LspInfoBorder = { link = "FloatBorder" },

    -- ── diagnostics ───────────────────────────────────────────
    DiagnosticError = { fg = p.red },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.blue },
    DiagnosticHint = { fg = p.teal },
    DiagnosticOk = { fg = p.green },
    DiagnosticVirtualTextError = { fg = p.red, bg = tint(p.red) },
    DiagnosticVirtualTextWarn = { fg = p.yellow, bg = tint(p.yellow) },
    DiagnosticVirtualTextInfo = { fg = p.blue, bg = tint(p.blue) },
    DiagnosticVirtualTextHint = { fg = p.teal, bg = tint(p.teal) },
    DiagnosticVirtualTextOk = { fg = p.green, bg = tint(p.green) },
    DiagnosticUnderlineError = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.teal, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
    DiagnosticUnnecessary = { fg = p.comment, italic = it },
    DiagnosticDeprecated = { strikethrough = true },

    -- ── lumen ui (statusline / tabline / dashboard) ───────────
    LumenStl = { fg = p.fg_dim, bg = p.bg_dark },
    LumenStlDim = { fg = p.comment, bg = p.bg_dark },
    LumenStlFile = { fg = p.fg_bright, bg = p.bg_dark, bold = true },
    LumenStlModified = { fg = p.accent, bg = p.bg_dark },
    LumenStlBranch = { fg = p.violet, bg = p.bg_dark, bold = true },
    LumenStlAdded = { fg = p.green, bg = p.bg_dark },
    LumenStlChanged = { fg = p.blue, bg = p.bg_dark },
    LumenStlRemoved = { fg = p.red, bg = p.bg_dark },
    LumenStlError = { fg = p.red, bg = p.bg_dark },
    LumenStlWarn = { fg = p.yellow, bg = p.bg_dark },
    LumenStlInfo = { fg = p.blue, bg = p.bg_dark },
    LumenStlHint = { fg = p.teal, bg = p.bg_dark },
    LumenStlLsp = { fg = p.fg_dim, bg = p.bg_dark },
    LumenStlProgress = { fg = p.accent, bg = p.bg_dark, italic = true },
    LumenStlRecording = { fg = p.red, bg = p.bg_dark, bold = true },
    LumenStlPos = { fg = p.fg, bg = p.bg_sel, bold = true },
    LumenStlPosSep = { fg = p.bg_sel, bg = p.bg_dark },

    LumenTab = { fg = p.comment, bg = p.bg_dark },
    LumenTabActive = { fg = p.fg_bright, bg = p.bg, bold = true },
    LumenTabActiveBar = { fg = p.accent, bg = p.bg },
    LumenTabModified = { fg = p.accent, bg = p.bg_dark },
    LumenTabActiveModified = { fg = p.accent, bg = p.bg },
    LumenTabClose = { fg = p.gutter, bg = p.bg_dark },
    LumenTabPage = { fg = p.comment, bg = p.bg_dark },
    LumenTabPageActive = { fg = p.bg_dark, bg = p.accent, bold = true },

    LumenLogo1 = { fg = blend(p.accent, p.fg_bright, 0.55), bold = true },
    LumenLogo2 = { fg = blend(p.accent, p.fg_bright, 0.75), bold = true },
    LumenLogo3 = { fg = p.accent, bold = true },
    LumenLogo4 = { fg = blend(p.accent, p.rose, 0.75), bold = true },
    LumenLogo5 = { fg = blend(p.accent, p.rose, 0.5), bold = true },
    LumenLogo6 = { fg = blend(p.accent, p.rose, 0.25), bold = true },
    LumenTagline = { fg = p.comment, italic = true },

    -- ── winbar / folds / multicursor ─────────────────────────
    LumenWinbar = { fg = p.comment, bg = bg },
    LumenWinbarFile = { fg = p.fg, bg = bg, bold = true },
    LumenWinbarSymbol = { fg = p.fg_dim, bg = bg },
    LumenWinbarSep = { fg = p.gutter, bg = bg },
    LumenFoldDots = { fg = p.accent, bg = p.bg_hl, bold = true },
    LumenFoldCount = { fg = p.comment, bg = p.bg_sel, italic = true },
    MCursor = { fg = p.bg_dark, bg = p.rose },
    LumenStlCursors = { fg = p.rose, bg = p.bg_dark, bold = true },

    -- ── snacks ────────────────────────────────────────────────
    SnacksNormal = { link = "NormalFloat" },
    SnacksWinBar = { link = "Title" },
    SnacksBackdrop = { bg = p.bg_dark },
    SnacksDashboardNormal = { fg = p.fg, bg = bg },
    SnacksDashboardHeader = { fg = p.accent, bold = true },
    SnacksDashboardIcon = { fg = p.accent },
    SnacksDashboardKey = { fg = p.accent, bold = true },
    SnacksDashboardDesc = { fg = p.fg },
    SnacksDashboardFile = { fg = p.fg },
    SnacksDashboardDir = { fg = p.comment },
    SnacksDashboardFooter = { fg = p.comment, italic = true },
    SnacksDashboardSpecial = { fg = p.violet },
    SnacksDashboardTitle = { fg = p.blue, bold = true },
    SnacksIndent = { fg = o.light and p.bg_sel or blend(p.bg_sel, p.bg, 0.8) },
    SnacksIndentScope = { fg = blend(p.accent, p.bg, 0.55) },
    SnacksIndentChunk = { fg = blend(p.accent, p.bg, 0.55) },
    SnacksNotifierInfo = { fg = p.fg, bg = bg_float },
    SnacksNotifierBorderInfo = { fg = p.blue, bg = bg_float },
    SnacksNotifierTitleInfo = { fg = p.blue, bold = true },
    SnacksNotifierIconInfo = { fg = p.blue },
    SnacksNotifierWarn = { fg = p.fg, bg = bg_float },
    SnacksNotifierBorderWarn = { fg = p.yellow, bg = bg_float },
    SnacksNotifierTitleWarn = { fg = p.yellow, bold = true },
    SnacksNotifierIconWarn = { fg = p.yellow },
    SnacksNotifierError = { fg = p.fg, bg = bg_float },
    SnacksNotifierBorderError = { fg = p.red, bg = bg_float },
    SnacksNotifierTitleError = { fg = p.red, bold = true },
    SnacksNotifierIconError = { fg = p.red },
    SnacksNotifierDebug = { fg = p.fg_dim, bg = bg_float },
    SnacksNotifierBorderDebug = { fg = p.border, bg = bg_float },
    SnacksNotifierTrace = { fg = p.fg_dim, bg = bg_float },
    SnacksNotifierBorderTrace = { fg = p.border, bg = bg_float },
    SnacksInputNormal = { link = "NormalFloat" },
    SnacksInputBorder = { fg = p.accent, bg = bg_float },
    SnacksInputTitle = { fg = p.bg_dark, bg = p.accent, bold = true },
    SnacksInputIcon = { fg = p.accent },
    SnacksPicker = { link = "NormalFloat" },
    SnacksPickerBorder = { fg = p.border, bg = bg_float },
    SnacksPickerTitle = { fg = p.bg_dark, bg = p.accent, bold = true },
    SnacksPickerInputBorder = { fg = p.accent, bg = bg_float },
    SnacksPickerInputTitle = { fg = p.bg_dark, bg = p.accent, bold = true },
    SnacksPickerPrompt = { fg = p.accent, bold = true },
    SnacksPickerPreviewTitle = { fg = p.bg_dark, bg = p.blue, bold = true },
    SnacksPickerListTitle = { fg = p.bg_dark, bg = p.violet, bold = true },
    SnacksPickerMatch = { fg = p.accent, bold = true },
    SnacksPickerDir = { fg = p.comment },
    SnacksPickerFile = { fg = p.fg },
    SnacksPickerCursorLine = { bg = p.bg_sel },
    SnacksPickerListCursorLine = { bg = p.bg_sel },
    SnacksPickerSelected = { fg = p.accent },
    SnacksPickerTotals = { fg = p.comment },
    SnacksPickerTree = { fg = p.gutter },
    SnacksPickerGitStatusUntracked = { fg = p.comment },
    SnacksScratchKey = { fg = p.bg_dark, bg = p.accent },
    SnacksZenIcon = { fg = p.accent },
    SnacksStatusColumnMark = { fg = p.accent, bold = true },

    -- ── blink.cmp ─────────────────────────────────────────────
    BlinkCmpMenu = { fg = p.fg, bg = bg_float },
    BlinkCmpMenuBorder = { fg = p.border, bg = bg_float },
    BlinkCmpMenuSelection = { bg = p.bg_sel, bold = true },
    BlinkCmpScrollBarThumb = { bg = p.border },
    BlinkCmpScrollBarGutter = { bg = bg_float },
    BlinkCmpLabel = { fg = p.fg },
    BlinkCmpLabelMatch = { fg = p.accent, bold = true },
    BlinkCmpLabelDeprecated = { fg = p.comment, strikethrough = true },
    BlinkCmpLabelDetail = { fg = p.comment },
    BlinkCmpLabelDescription = { fg = p.comment },
    BlinkCmpKind = { fg = p.violet },
    BlinkCmpSource = { fg = p.gutter },
    BlinkCmpGhostText = { fg = p.gutter, italic = true },
    BlinkCmpDoc = { fg = p.fg, bg = bg_float },
    BlinkCmpDocBorder = { fg = p.border, bg = bg_float },
    BlinkCmpDocSeparator = { fg = p.border, bg = bg_float },
    BlinkCmpSignatureHelp = { fg = p.fg, bg = bg_float },
    BlinkCmpSignatureHelpBorder = { fg = p.border, bg = bg_float },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },

    -- ── which-key ─────────────────────────────────────────────
    WhichKey = { fg = p.accent, bold = true },
    WhichKeyGroup = { fg = p.violet },
    WhichKeyDesc = { fg = p.fg },
    WhichKeySeparator = { fg = p.gutter },
    WhichKeyNormal = { link = "NormalFloat" },
    WhichKeyBorder = { link = "FloatBorder" },
    WhichKeyTitle = { link = "FloatTitle" },
    WhichKeyValue = { fg = p.comment },

    -- ── git ───────────────────────────────────────────────────
    GitSignsAdd = { fg = p.green },
    GitSignsChange = { fg = p.blue },
    GitSignsDelete = { fg = p.red },
    GitSignsUntracked = { fg = p.gutter },
    GitSignsAddInline = { bg = tint(p.green, 0.3) },
    GitSignsChangeInline = { bg = tint(p.blue, 0.3) },
    GitSignsDeleteInline = { bg = tint(p.red, 0.3) },
    GitSignsCurrentLineBlame = { fg = p.gutter, italic = it },

    -- ── flash ─────────────────────────────────────────────────
    FlashBackdrop = { fg = p.comment },
    FlashMatch = { fg = p.fg_bright, bg = p.bg_sel },
    FlashCurrent = { fg = p.bg_dark, bg = p.yellow },
    FlashLabel = { fg = p.bg_dark, bg = p.rose, bold = true },

    -- ── mini ──────────────────────────────────────────────────
    MiniIconsAzure = { fg = p.sky },
    MiniIconsBlue = { fg = p.blue },
    MiniIconsCyan = { fg = p.cyan },
    MiniIconsGreen = { fg = p.green },
    MiniIconsGrey = { fg = p.fg_dim },
    MiniIconsOrange = { fg = p.orange },
    MiniIconsPurple = { fg = p.violet },
    MiniIconsRed = { fg = p.red },
    MiniIconsYellow = { fg = p.yellow },
    MiniSurround = { link = "IncSearch" },
    MiniHipatternsFixme = { link = "@comment.error" },
    MiniHipatternsHack = { link = "@comment.warning" },
    MiniHipatternsTodo = { link = "@comment.todo" },
    MiniHipatternsNote = { link = "@comment.note" },

    -- ── trouble / todo / grug-far / lazy / mason ──────────────
    TroubleNormal = { fg = p.fg, bg = bg },
    TroubleNormalNC = { fg = p.fg, bg = bg },
    TroubleCount = { fg = p.accent, bg = p.bg_sel, bold = true },
    TroubleText = { fg = p.fg },
    TodoBgTODO = { fg = p.bg_dark, bg = p.accent, bold = true },
    TodoFgTODO = { fg = p.accent },
    LazyNormal = { link = "NormalFloat" },
    LazyButton = { fg = p.fg, bg = p.bg_sel },
    LazyButtonActive = { fg = p.bg_dark, bg = p.accent, bold = true },
    LazyH1 = { fg = p.bg_dark, bg = p.accent, bold = true },
    LazyH2 = { fg = p.accent, bold = true },
    LazySpecial = { fg = p.violet },
    LazyProgressDone = { fg = p.accent },
    LazyProgressTodo = { fg = p.border },
    LazyReasonEvent = { fg = p.yellow },
    LazyReasonPlugin = { fg = p.rose },
    LazyReasonKeys = { fg = p.teal },
    LazyReasonCmd = { fg = p.cyan },
    LazyReasonFt = { fg = p.violet },
    LazyReasonStart = { fg = p.green },
    MasonNormal = { link = "NormalFloat" },
    MasonHeader = { fg = p.bg_dark, bg = p.accent, bold = true },
    MasonHighlight = { fg = p.accent },
    MasonHighlightBlock = { fg = p.bg_dark, bg = p.accent },
    MasonHighlightBlockBold = { fg = p.bg_dark, bg = p.accent, bold = true },
    MasonMuted = { fg = p.comment },
    MasonMutedBlock = { fg = p.fg_dim, bg = p.bg_sel },

    -- ── render-markdown ───────────────────────────────────────
    RenderMarkdownH1Bg = { bg = tint(p.amber, 0.14) },
    RenderMarkdownH2Bg = { bg = tint(p.blue, 0.12) },
    RenderMarkdownH3Bg = { bg = tint(p.violet, 0.12) },
    RenderMarkdownH4Bg = { bg = tint(p.teal, 0.12) },
    RenderMarkdownH5Bg = { bg = tint(p.rose, 0.12) },
    RenderMarkdownH6Bg = { bg = tint(p.orange, 0.12) },
    RenderMarkdownCode = { bg = p.bg_float },
    RenderMarkdownCodeInline = { fg = p.green, bg = p.bg_float },
    RenderMarkdownBullet = { fg = p.amber },
    RenderMarkdownTableHead = { fg = p.amber },
    RenderMarkdownTableRow = { fg = p.border },

    -- ── oil ───────────────────────────────────────────────────
    OilDir = { fg = p.blue, bold = true },
    OilDirIcon = { fg = p.blue },
    OilLink = { fg = p.cyan },
    OilCreate = { fg = p.green },
    OilDelete = { fg = p.red },
    OilMove = { fg = p.yellow },
    OilCopy = { fg = p.teal },
    OilChange = { fg = p.blue },
  }

  for _, mode in ipairs({
    { "Normal", p.accent },
    { "Insert", p.green },
    { "Visual", p.violet },
    { "Replace", p.red },
    { "Command", p.cyan },
    { "Terminal", p.teal },
  }) do
    g["LumenStlMode" .. mode[1]] = { fg = p.bg_dark, bg = mode[2], bold = true }
    g["LumenStlMode" .. mode[1] .. "Sep"] = { fg = mode[2], bg = p.bg_dark }
  end

  -- scrollbar: track, viewport thumb, and marks (with a variant drawn on the thumb)
  g.LumenScrollTrack = { bg = bg }
  g.LumenScrollThumb = { bg = p.bg_sel }
  for name, color in pairs({
    Error = p.red,
    Warn = p.yellow,
    Info = p.blue,
    Hint = p.teal,
    Add = p.green,
    Change = p.blue,
    Delete = p.red,
    Search = p.accent,
    Cursors = p.rose,
  }) do
    g["LumenScroll" .. name] = { fg = color, bg = bg }
    g["LumenScroll" .. name .. "Thumb"] = { fg = color, bg = p.bg_sel }
  end
  g.LumenStlTask = { fg = p.teal, bg = p.bg_dark, italic = true }

  if o.transparent then
    for _, name in ipairs({ "StatusLine", "StatusLineNC", "TabLineFill", "LumenStl", "LumenTab" }) do
      g[name] = vim.tbl_extend("force", g[name], { bg = "NONE" })
    end
  end

  return g
end

return M
